### ISSUE TITLE
Table: Style issues

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#266]
**1. Footer style improper if total records < pageSize**

If total records is less than pageSize, table footer looks as below,

<img width="1106" alt="tf1" src="https://user-images.githubusercontent.com/24920919/67339895-fd3d1080-f4e0-11e9-9379-ba07a01c1230.png">

If zero records, then is ok
<img width="1105" alt="tf2" src="https://user-images.githubusercontent.com/24920919/67339943-0e861d00-f4e1-11e9-8211-f05f623d22c1.png">

The below check needs to be fixed, theres a special condition of zero records alone,

<img width="1261" alt="Screen Shot 2019-10-22 at 3 27 14 PM" src="https://user-images.githubusercontent.com/24920919/67339958-1ba30c00-f4e1-11e9-83f2-3f7c9dd34f2f.png">

**2. Table style not proper in certain scenarios**

Sample:
![tableStyle1](https://user-images.githubusercontent.com/24920919/67417041-cae0f100-f57c-11e9-9d62-e46fd9a8c987.gif)

The above table corresponds to **vsd-from-nsgs-table** in https://github.com/nuagenetworks/vis-config/blob/master/dashboards/aarNetworkPerformance.json

`this.state.data` in Table:
```
[
  {
    "row_id":464495045301,
    "name":"ovs-1"
  },
  {
    "row_id":159756482911,
    "name":"ovs-2"
  },
  {
    "row_id":62776756039,
    "name":"ovs-3"
  },
  {
    "row_id":1189580043768,
    "name":"ovs-4"
  },
  {
    "row_id":201568011744,
    "name":"ovs-6"
  },
  {
    "row_id":1286210961973,
    "name":"ovs-7"
  }
]
```
 
**3. With scroll enabled - refresh button overlaps with filter + same issue 2 above**

Sample:
<img width="556" alt="Screen Shot 2019-10-23 at 10 10 40 AM" src="https://user-images.githubusercontent.com/24920919/67417409-8b66d480-f57d-11e9-9d2a-e6293533810a.png">

**4 Row selection issue: select a row and then select something else on a different visualization, the selection is not persisted. Have a look at the gif attached:

![Uploading table-selection-issue.gif…]()

**Comment by killanch** [comment]
@nxjiten can you pls have a look?
cc @natabal

**Comment by killanch** [comment]
@nxjiten Can you pls address the 2 additional issues I have reported above. These are with your latest changes in https://github.com/nuagenetworks/vis-graphs/pull/268

**Comment by natabal** [comment]
@nxjiten These issue needs to be addressed ASAP.

**Comment by nxjiten** [comment]
@natabal
Issue has been fixed. Please have a look.

**Comment by killanch** [comment]
@nxjiten @natabal My observations based on latest changes in https://github.com/nuagenetworks/vis-graphs/pull/268

**Issue 1:** Appears better, but still not perfect. See table bottom alignment issue in sample screenshots below,
<img width="1107" alt="issue1 1" src="https://user-images.githubusercontent.com/24920919/67881413-b319e780-fafd-11e9-9943-7983078fd303.png">
<img width="1111" alt="issue1 2" src="https://user-images.githubusercontent.com/24920919/67881418-b7460500-fafd-11e9-8023-81c245ea3553.png">

**Issue 2:** Fixed. Sample below,
![issue2](https://user-images.githubusercontent.com/24920919/67881494-d5ac0080-fafd-11e9-8ad5-b3413e91af18.gif)

**Issue 3:** Button overlap and table alignment issues seem fixed now. But I now notice additional white space below the button/filters when scroll is enabled. Sample below, the visualization on the left has scroll enabled, while the one on the right has no scroll.
<img width="1107" alt="issue3 1" src="https://user-images.githubusercontent.com/24920919/67881645-1ad03280-fafe-11e9-9f24-8ba3d6637e95.png">
<img width="1107" alt="issue3 2" src="https://user-images.githubusercontent.com/24920919/67881646-1ad03280-fafe-11e9-8719-e30eb9753c2f.png">

**Issue 4:** Refresh button appears in the title row along with download and share buttons in certain configs (sample in Issue 1 above), and along with filter in certain configs (sample in Issue 3 above). Can we make them consistent, always to be rendered along with download and share buttons?

**Issue 5:** On some tables, after initial loading, it requires two clicks for the row selection text to appear for the first time. Sample below,
![rowselect](https://user-images.githubusercontent.com/24920919/67884140-887e5d80-fb02-11e9-8b0d-953d00b059f9.gif)

**Comment by nxjiten** [comment]
@killanch 
Fix all the latest issues. Please have a look.

**Comment by nxjiten** [comment]
On issue 7 - This is configurable, you may remove resizable feature from the dashboard configuration by setting `static: true` property.

Issue 6 has been fixed and commit the changes in PR #268

**Comment by killanch** [comment]
@nxjiten All above issues appear to have been fixed now. Thanks.
@natabal Pls confirm if we can go ahead and merge
